schema_version: 1

context:
  name: cxxheaderparser
  version: "1.8.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/cxxheaderparser-${{ version }}.tar.gz
  sha256: 683a30888731062b1b2d8249568e87c585e3d80e7d62c8c9a1fccfb4c9665d2b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - cxxheaderparser
      pip_check: true

about:
  summary: Parse C++ header files and generate a data structure representing the class
  license: BSD-2-Clause
  license_file: LICENSE.txt
  homepage: https://github.com/robotpy/cxxheaderparser

extra:
  recipe-maintainers:
    - xhochy
